// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: deliveries.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getPendingDeliveries = `-- name: GetPendingDeliveries :many
SELECT
  d.id, d.org_id, d.event_id, d.subscription_id, d.status,
  d.attempts, d.max_attempts, d.next_retry_at, d.last_error,
  d.delivered_at, d.created_at,
  s.name AS subscription_name, s.channel_type, s.channel_config,
  e.event_type, e.payload AS event_payload
FROM deliveries d
JOIN subscriptions s ON s.id = d.subscription_id
JOIN events e ON e.id = d.event_id
WHERE d.status = 'pending'
  AND d.next_retry_at <= now()
ORDER BY d.next_retry_at ASC
LIMIT 50
`

type GetPendingDeliveriesRow struct {
	ID               pgtype.UUID        `json:"id"`
	OrgID            string             `json:"org_id"`
	EventID          pgtype.UUID        `json:"event_id"`
	SubscriptionID   pgtype.UUID        `json:"subscription_id"`
	Status           string             `json:"status"`
	Attempts         int32              `json:"attempts"`
	MaxAttempts      int32              `json:"max_attempts"`
	NextRetryAt      pgtype.Timestamptz `json:"next_retry_at"`
	LastError        pgtype.Text        `json:"last_error"`
	DeliveredAt      pgtype.Timestamptz `json:"delivered_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	SubscriptionName string             `json:"subscription_name"`
	ChannelType      string             `json:"channel_type"`
	ChannelConfig    []byte             `json:"channel_config"`
	EventType        string             `json:"event_type"`
	EventPayload     []byte             `json:"event_payload"`
}

func (q *Queries) GetPendingDeliveries(ctx context.Context) ([]GetPendingDeliveriesRow, error) {
	rows, err := q.db.Query(ctx, getPendingDeliveries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetPendingDeliveriesRow{}
	for rows.Next() {
		var i GetPendingDeliveriesRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.EventID,
			&i.SubscriptionID,
			&i.Status,
			&i.Attempts,
			&i.MaxAttempts,
			&i.NextRetryAt,
			&i.LastError,
			&i.DeliveredAt,
			&i.CreatedAt,
			&i.SubscriptionName,
			&i.ChannelType,
			&i.ChannelConfig,
			&i.EventType,
			&i.EventPayload,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertDelivery = `-- name: InsertDelivery :one
INSERT INTO deliveries (org_id, event_id, subscription_id, status, attempts, max_attempts, next_retry_at)
VALUES ($1, $2, $3, 'pending', 0, 5, now())
RETURNING id, org_id, event_id, subscription_id, status, attempts, max_attempts, next_retry_at, last_error, delivered_at, created_at
`

type InsertDeliveryParams struct {
	OrgID          string      `json:"org_id"`
	EventID        pgtype.UUID `json:"event_id"`
	SubscriptionID pgtype.UUID `json:"subscription_id"`
}

func (q *Queries) InsertDelivery(ctx context.Context, arg InsertDeliveryParams) (Delivery, error) {
	row := q.db.QueryRow(ctx, insertDelivery, arg.OrgID, arg.EventID, arg.SubscriptionID)
	var i Delivery
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.EventID,
		&i.SubscriptionID,
		&i.Status,
		&i.Attempts,
		&i.MaxAttempts,
		&i.NextRetryAt,
		&i.LastError,
		&i.DeliveredAt,
		&i.CreatedAt,
	)
	return i, err
}

const markDeliveryDelivered = `-- name: MarkDeliveryDelivered :exec
UPDATE deliveries
SET status = 'delivered',
    delivered_at = now(),
    attempts = attempts + 1
WHERE id = $1
`

func (q *Queries) MarkDeliveryDelivered(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markDeliveryDelivered, id)
	return err
}

const markDeliveryFailed = `-- name: MarkDeliveryFailed :exec
UPDATE deliveries
SET status = 'failed',
    attempts = attempts + 1,
    last_error = $2
WHERE id = $1
`

type MarkDeliveryFailedParams struct {
	ID        pgtype.UUID `json:"id"`
	LastError pgtype.Text `json:"last_error"`
}

func (q *Queries) MarkDeliveryFailed(ctx context.Context, arg MarkDeliveryFailedParams) error {
	_, err := q.db.Exec(ctx, markDeliveryFailed, arg.ID, arg.LastError)
	return err
}

const markDeliveryRetry = `-- name: MarkDeliveryRetry :exec
UPDATE deliveries
SET attempts = attempts + 1,
    next_retry_at = $2,
    last_error = $3
WHERE id = $1
`

type MarkDeliveryRetryParams struct {
	ID          pgtype.UUID        `json:"id"`
	NextRetryAt pgtype.Timestamptz `json:"next_retry_at"`
	LastError   pgtype.Text        `json:"last_error"`
}

func (q *Queries) MarkDeliveryRetry(ctx context.Context, arg MarkDeliveryRetryParams) error {
	_, err := q.db.Exec(ctx, markDeliveryRetry, arg.ID, arg.NextRetryAt, arg.LastError)
	return err
}
