// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: events.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getEventsByOrg = `-- name: GetEventsByOrg :many
SELECT id, org_id, event_type, watch_id, watch_run_id, entity_id, payload, occurred_at FROM events
WHERE org_id = $1
ORDER BY occurred_at DESC
LIMIT $2 OFFSET $3
`

type GetEventsByOrgParams struct {
	OrgID  string `json:"org_id"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

func (q *Queries) GetEventsByOrg(ctx context.Context, arg GetEventsByOrgParams) ([]Event, error) {
	rows, err := q.db.Query(ctx, getEventsByOrg, arg.OrgID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Event{}
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.EventType,
			&i.WatchID,
			&i.WatchRunID,
			&i.EntityID,
			&i.Payload,
			&i.OccurredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEventsByWatch = `-- name: GetEventsByWatch :many
SELECT id, org_id, event_type, watch_id, watch_run_id, entity_id, payload, occurred_at FROM events
WHERE org_id = $1 AND watch_id = $2
ORDER BY occurred_at DESC
LIMIT $3 OFFSET $4
`

type GetEventsByWatchParams struct {
	OrgID   string      `json:"org_id"`
	WatchID pgtype.UUID `json:"watch_id"`
	Limit   int32       `json:"limit"`
	Offset  int32       `json:"offset"`
}

func (q *Queries) GetEventsByWatch(ctx context.Context, arg GetEventsByWatchParams) ([]Event, error) {
	rows, err := q.db.Query(ctx, getEventsByWatch,
		arg.OrgID,
		arg.WatchID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Event{}
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.EventType,
			&i.WatchID,
			&i.WatchRunID,
			&i.EntityID,
			&i.Payload,
			&i.OccurredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertEvent = `-- name: InsertEvent :one
INSERT INTO events (org_id, event_type, watch_id, watch_run_id, entity_id, payload, occurred_at)
VALUES ($1, $2, $3, $4, $5, $6, now())
RETURNING id, org_id, event_type, watch_id, watch_run_id, entity_id, payload, occurred_at
`

type InsertEventParams struct {
	OrgID      string      `json:"org_id"`
	EventType  string      `json:"event_type"`
	WatchID    pgtype.UUID `json:"watch_id"`
	WatchRunID pgtype.UUID `json:"watch_run_id"`
	EntityID   pgtype.UUID `json:"entity_id"`
	Payload    []byte      `json:"payload"`
}

func (q *Queries) InsertEvent(ctx context.Context, arg InsertEventParams) (Event, error) {
	row := q.db.QueryRow(ctx, insertEvent,
		arg.OrgID,
		arg.EventType,
		arg.WatchID,
		arg.WatchRunID,
		arg.EntityID,
		arg.Payload,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.EventType,
		&i.WatchID,
		&i.WatchRunID,
		&i.EntityID,
		&i.Payload,
		&i.OccurredAt,
	)
	return i, err
}
