// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Blueprint struct {
	ID              pgtype.UUID        `json:"id"`
	OrgID           string             `json:"org_id"`
	Name            string             `json:"name"`
	Url             string             `json:"url"`
	SchemaType      string             `json:"schema_type"`
	ExtractionRules []byte             `json:"extraction_rules"`
	Status          string             `json:"status"`
	Version         int32              `json:"version"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	DeletedAt       pgtype.Timestamptz `json:"deleted_at"`
}

type Entity struct {
	ID          pgtype.UUID        `json:"id"`
	OrgID       string             `json:"org_id"`
	WatchID     pgtype.UUID        `json:"watch_id"`
	SchemaType  string             `json:"schema_type"`
	ExternalID  string             `json:"external_id"`
	Content     []byte             `json:"content"`
	Url         pgtype.Text        `json:"url"`
	Status      string             `json:"status"`
	FirstSeenAt pgtype.Timestamptz `json:"first_seen_at"`
	LastSeenAt  pgtype.Timestamptz `json:"last_seen_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type Event struct {
	ID         pgtype.UUID        `json:"id"`
	OrgID      string             `json:"org_id"`
	EventType  string             `json:"event_type"`
	WatchID    pgtype.UUID        `json:"watch_id"`
	WatchRunID pgtype.UUID        `json:"watch_run_id"`
	EntityID   pgtype.UUID        `json:"entity_id"`
	Payload    []byte             `json:"payload"`
	OccurredAt pgtype.Timestamptz `json:"occurred_at"`
}

type Watch struct {
	ID                  pgtype.UUID        `json:"id"`
	OrgID               string             `json:"org_id"`
	BlueprintID         pgtype.UUID        `json:"blueprint_id"`
	Name                string             `json:"name"`
	Url                 string             `json:"url"`
	Schedule            string             `json:"schedule"`
	IdentityFields      []string           `json:"identity_fields"`
	Status              string             `json:"status"`
	NextRunAt           pgtype.Timestamptz `json:"next_run_at"`
	ConsecutiveFailures int32              `json:"consecutive_failures"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	DeletedAt           pgtype.Timestamptz `json:"deleted_at"`
}

type WatchRun struct {
	ID              pgtype.UUID        `json:"id"`
	OrgID           string             `json:"org_id"`
	WatchID         pgtype.UUID        `json:"watch_id"`
	Status          string             `json:"status"`
	StartedAt       pgtype.Timestamptz `json:"started_at"`
	CompletedAt     pgtype.Timestamptz `json:"completed_at"`
	EntitiesFound   pgtype.Int4        `json:"entities_found"`
	EntitiesNew     pgtype.Int4        `json:"entities_new"`
	EntitiesChanged pgtype.Int4        `json:"entities_changed"`
	EntitiesRemoved pgtype.Int4        `json:"entities_removed"`
	EventsEmitted   pgtype.Int4        `json:"events_emitted"`
	ErrorMessage    pgtype.Text        `json:"error_message"`
}
