// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: subscriptions.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const matchSubscriptions = `-- name: MatchSubscriptions :many
SELECT id, org_id, name, event_types, watch_id, filters, channel_type, channel_config, status, created_at, updated_at, deleted_at FROM subscriptions
WHERE org_id = $1
  AND status = 'active'
  AND deleted_at IS NULL
  AND $2::text = ANY(event_types)
  AND (watch_id IS NULL OR watch_id = $3)
ORDER BY created_at ASC
`

type MatchSubscriptionsParams struct {
	OrgID   string      `json:"org_id"`
	Column2 string      `json:"column_2"`
	WatchID pgtype.UUID `json:"watch_id"`
}

func (q *Queries) MatchSubscriptions(ctx context.Context, arg MatchSubscriptionsParams) ([]Subscription, error) {
	rows, err := q.db.Query(ctx, matchSubscriptions, arg.OrgID, arg.Column2, arg.WatchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Subscription{}
	for rows.Next() {
		var i Subscription
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.EventTypes,
			&i.WatchID,
			&i.Filters,
			&i.ChannelType,
			&i.ChannelConfig,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
