// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: watch_runs.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const completeWatchRun = `-- name: CompleteWatchRun :exec
UPDATE watch_runs
SET status = $2,
    completed_at = now(),
    entities_found = $3,
    entities_new = $4,
    entities_changed = $5,
    entities_removed = $6,
    events_emitted = $7,
    error_message = $8
WHERE id = $1
`

type CompleteWatchRunParams struct {
	ID              pgtype.UUID `json:"id"`
	Status          string      `json:"status"`
	EntitiesFound   pgtype.Int4 `json:"entities_found"`
	EntitiesNew     pgtype.Int4 `json:"entities_new"`
	EntitiesChanged pgtype.Int4 `json:"entities_changed"`
	EntitiesRemoved pgtype.Int4 `json:"entities_removed"`
	EventsEmitted   pgtype.Int4 `json:"events_emitted"`
	ErrorMessage    pgtype.Text `json:"error_message"`
}

func (q *Queries) CompleteWatchRun(ctx context.Context, arg CompleteWatchRunParams) error {
	_, err := q.db.Exec(ctx, completeWatchRun,
		arg.ID,
		arg.Status,
		arg.EntitiesFound,
		arg.EntitiesNew,
		arg.EntitiesChanged,
		arg.EntitiesRemoved,
		arg.EventsEmitted,
		arg.ErrorMessage,
	)
	return err
}

const createWatchRun = `-- name: CreateWatchRun :one
INSERT INTO watch_runs (org_id, watch_id, status, started_at)
VALUES ($1, $2, 'running', now())
RETURNING id, org_id, watch_id, status, started_at, completed_at, entities_found, entities_new, entities_changed, entities_removed, events_emitted, error_message
`

type CreateWatchRunParams struct {
	OrgID   string      `json:"org_id"`
	WatchID pgtype.UUID `json:"watch_id"`
}

func (q *Queries) CreateWatchRun(ctx context.Context, arg CreateWatchRunParams) (WatchRun, error) {
	row := q.db.QueryRow(ctx, createWatchRun, arg.OrgID, arg.WatchID)
	var i WatchRun
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.WatchID,
		&i.Status,
		&i.StartedAt,
		&i.CompletedAt,
		&i.EntitiesFound,
		&i.EntitiesNew,
		&i.EntitiesChanged,
		&i.EntitiesRemoved,
		&i.EventsEmitted,
		&i.ErrorMessage,
	)
	return i, err
}
