run:
  timeout: 3m

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - ineffassign
    - goimports
    - gofmt
    - gocritic

linters-settings:
  goimports:
    local-prefixes: github.com/blueprinter/worker
  gocritic:
    enabled-tags:
      - diagnostic
      - performance

issues:
  exclude-use-default: true
  max-issues-per-linter: 50
  max-same-issues: 10
